[service]
    address = '127.0.0.1'
    port = 8340
    sslKey = 'classpath:ssl.key'
    sslCert = 'classpath:ssl.crt'
    caCert = 'classpath:ca.crt'
    sslOn = false

[auth]
    # for issuing token
    name = 'org1'
    secret = '123456'
    expires = 600 # 10 min

